package tagtime.quartz;

import org.quartz.impl.JobDetailImpl;

import tagtime.TagTime;

public class TagTimeJobDetailImpl extends JobDetailImpl {
	//generated by Eclipse
	private static final long serialVersionUID = 2264932025491480531L;
	
	private TagTime tagTimeInstance;
	
	public TagTimeJobDetailImpl() {
	}
	
	public void setTagTimeInstance(TagTime instance) {
		if(instance == null) {
			throw new IllegalArgumentException("TagTime instance cannot " +
						"be null.");
		}
		tagTimeInstance = instance;
	}
	
	public TagTime getTagTimeInstance() {
		return tagTimeInstance;
	}
}
